### ISSUE TITLE
Message: Element <input id="identifierId" name="identifierInput" type="hidden"> is not reachable by keyboard

### ISSUE THREAD

**Issue by Soulofdestiny** [Leopounet/GeoGuessr#1]
Hey Mate,

Happy new year and all the best to you!

first of all thanks for this bot, wanted to bring this to our discord server to make it easier for non-pro users to get challenges without having me available.

setting it up went smooth and the bot is reacting to commands on the discord server.
However when trying to generate a link for a challenge, it is not responding and the debug output of the Server is giving me:
`Message: Element <input id="identifierId" name="identifierInput" type="hidden"> is not reachable by keyboard`

Since I am not really experienced with Selenium I have not really a clue where to start with debugging this.
I assume it is because a recent change on the login page of geoguessr, no?

hope you can give me some hints.

cheers,
Matthias

**Comment by Leopounet** [comment]
Hi,

Can you tell me which map generated this error? Unfortunately, I can't reproduce the error (it works on my computer). In the code of `BotGeoguessr.py` you should find line 30 `options.headless = True`, set it to False and restart the bot, this should show when the bot fails, let me know where it fails.

Cheers

**Comment by Soulofdestiny** [comment]
so I have tried with multiple maps, e.g.
`!!generate https://www.geoguessr.com/maps/59a1514f17631e74145b6f47`
`!!generate https://www.geoguessr.com/maps/world `
`!!generate https://www.geoguessr.com/maps/uk `

however, the error message about this  `Message: Element <input id="identifierId" name="identifierInput" type="hidden"> is not reachable by keyboard` only occurs when trying to generate the first link after starting the bot.
(though no map is working and giving me an actual challenge link)

setting `options.headless = False` gives me (after approx. 3seconds).
(not entirely sure tbh if I execute it correctly in headless mode?)

```
(guessr)phelius@v22017084841152154:~/geoguessr_bot/Geoguessr/guessr/BotGenerateGeoguessrLink> python BotGeoguessr.py
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/phelius/geoguessr_bot/Geoguessr/guessr/lib/python3.6/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "BotGeoguessr.py", line 34, in on_ready
    self.driver = webdriver.Firefox(options=options)
  File "/home/phelius/geoguessr_bot/Geoguessr/guessr/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/phelius/geoguessr_bot/Geoguessr/guessr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/phelius/geoguessr_bot/Geoguessr/guessr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/phelius/geoguessr_bot/Geoguessr/guessr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/phelius/geoguessr_bot/Geoguessr/guessr/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
```

When I then try to execute commands, I get: 
`'MyClient' object has no attribute 'commands'`

**Comment by Leopounet** [comment]
On the computer you tried to start the bot, do you have a graphical interface? If not then the line `options.headless = True` can't be set to False (which could explain the new error you had). If you indeed don't have a graphical interface, please try running it on a computer with a graphical interface with headless set to False once again.

Otherwise, another problem could be that you are using python2 (sometimes it is not clear which version you are using), you can force the use of python3 by typing `python3 <you_file>`. 

On a side note, I am currently working on a big refactor of the source code (I didn't actually think people would use my code, so I coded a bit poorly). So maybe once I'm done with it, it will work, I don't know. Anyway, let me know if any of the two things I stated above changed anything. This probably won't fix the original issue, but hopefully at least you will be able to start the graphical version of selenium and see what happens so we can further investigate.

**Comment by Soulofdestiny** [comment]
yeah.. that makes sense... running it on my server with no graphic stack.

so we can rule out python version at least:

```
(guessr)phelius@v22017084841152154:~/geoguessr_bot/Geoguessr/guessr/BotGenerateGeoguessrLink> which python
/home/phelius/geoguessr_bot/Geoguessr/guessr/bin/python
(guessr)phelius@v22017084841152154:~/geoguessr_bot/Geoguessr/guessr/BotGenerateGeoguessrLink> /home/phelius/geoguessr_bot/Geoguessr/guessr/bin/python --version
Python 3.6.12
```

have also tried to execute it with full path, same behaviour

Thanks for the hints, will try tomorrow morning on my notebook and come back to you.

yeah funny coincident... we were playing geoguessr for a while and I'm the only one with pro account.
And since we use discord as main communication I thought it would be a cool idea to have something which can be used by my friends to play without me - discord bot was the closest idea for that :)
but you know, working in opensource company gives you the mindset that you should at least check github before ;)

I'm happy to test your refractoring and eventually even to contribute to it someday :)

will let you know my findings

**Comment by Soulofdestiny** [comment]
Good morning!

thanks for the refactoring :)  was faster than I thought.

so I set everything up on my notebook and run in non-headless mode which basically explains what's going wrong
so the default log in method is hardcoded to use google as far as I can see.

since I use plain login via mail and pw, it's not a surprise that it can not log me in, hence not generate any challenge :)

I suggest a new variable in Utils.py to choose between login methods.
I will try to come up with something, but based on my little knowledge of selenium and web-development, this might take a while :)

**Comment by Leopounet** [comment]
I hope when this works you and your friends can have fun with the bot! Don't hesitate to customize it.

I added different login methods and updated the README but basically took your idea that was good. There is now a new variable that you can set (it still defaults to google, but you can set it to classic or facebook). Hopefully this now works for you, let me know if something still doesn't work.

Also, if you are interested in learning selenium, it's pretty easy so go ahead, I'm not doing anything fancy here. :p

**Comment by Soulofdestiny** [comment]
hehe... actually I was just about to open a PR, since it was quite straight forward.
anyway you were faster (and your solution is better, although quite similiar to mine) :)

Thanks for your fast responses and help, I will let you know once I encounter any more issues or have suggestions for improvement.

cheers mate!
